/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author RojeruSan
 */
public class pnlHome extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnlHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        btn_facebook = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_instagram = new javax.swing.JButton();
        btn_linkedin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_mision = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 110, 186));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bienvenido a soluciones DD");

        btn_facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_facebook_50px.png"))); // NOI18N
        btn_facebook.setBorder(null);
        btn_facebook.setBorderPainted(false);
        btn_facebook.setContentAreaFilled(false);
        btn_facebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_facebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_facebookMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Siguenos en nuestras redes sociales");

        btn_instagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_instagram_50px.png"))); // NOI18N
        btn_instagram.setBorder(null);
        btn_instagram.setBorderPainted(false);
        btn_instagram.setContentAreaFilled(false);
        btn_instagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_instagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_instagramMouseClicked(evt);
            }
        });

        btn_linkedin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_linkedin_circled_50px.png"))); // NOI18N
        btn_linkedin.setBorder(null);
        btn_linkedin.setBorderPainted(false);
        btn_linkedin.setContentAreaFilled(false);
        btn_linkedin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_linkedin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_linkedinMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Misión");

        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");

        textarea_mision.setEditable(false);
        textarea_mision.setBackground(new java.awt.Color(255, 255, 255));
        textarea_mision.setColumns(20);
        textarea_mision.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textarea_mision.setForeground(new java.awt.Color(0, 0, 0));
        textarea_mision.setRows(5);
        textarea_mision.setText("Nuestra mision es darles el mejor trato a nuestros clientes, ayudandoles \na resolver sus tareas para que no reprueben esa es nuestra mision.\n");
        jScrollPane1.setViewportView(textarea_mision);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_facebook)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_instagram)
                                .addGap(62, 62, 62)
                                .addComponent(btn_linkedin))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_facebook)
                    .addComponent(btn_instagram)
                    .addComponent(btn_linkedin))
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_facebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_facebookMouseClicked
        try {
            Abrir_facebook();
        } catch (URISyntaxException ex) {
            java.util.logging.Logger.getLogger(pnlHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_facebookMouseClicked

    private void btn_instagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_instagramMouseClicked
        try {
            Abrir_instagram();
        } catch (URISyntaxException ex) {
            java.util.logging.Logger.getLogger(pnlHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_instagramMouseClicked

    private void btn_linkedinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_linkedinMouseClicked
        try {
            Abrir_linkedin();
        } catch (URISyntaxException ex) {
            java.util.logging.Logger.getLogger(pnlHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_linkedinMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_facebook;
    private javax.swing.JButton btn_instagram;
    private javax.swing.JButton btn_linkedin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textarea_mision;
    // End of variables declaration//GEN-END:variables

     private void Abrir_facebook() throws URISyntaxException {
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                URI uri = new URI("https://www.facebook.com/");
                desktop.browse(uri);
            } catch (IOException e) {
                System.err.println("Error: No se pudo abrir el enlace" + e.getMessage());
            }
        } else {
            System.err.println("Error: No se puede abrir enlaces web.");
        }
    }
     private void Abrir_instagram() throws URISyntaxException {
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                URI uri = new URI("https://www.instagram.com/");
                desktop.browse(uri);
            } catch (IOException e) {
                System.err.println("Error: No se pudo abrir el enlace" + e.getMessage());
            }
        } else {
            System.err.println("Error: No se puede abrir enlaces web.");
        }
    }
     private void Abrir_linkedin() throws URISyntaxException {
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                URI uri = new URI("https://www.linkedin.com/");
                desktop.browse(uri);
            } catch (IOException e) {
                System.err.println("Error: No se pudo abrir el enlace" + e.getMessage());
            }
        } else {
            System.err.println("Error: No se puede abrir enlaces web.");
        }
    }
}
