/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import ventanas.Frm_PrincipalUsuarios;
import conexion.Conexion;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author RojeruSan
 */
public class pnlHacerPedido extends javax.swing.JPanel {

    /**
     * layout: 641, 463
     */
    String user = Frm_PrincipalUsuarios.user;
    String cliente = "", correo = "", mensaje = "", numero = "";
    String estado = "";
    File fichero;
    FileInputStream fis;
    public static String nombreArchivo = "";

    public pnlHacerPedido() {
        initComponents();
        txt_cliente.setText(user);
        txt_contactoCelular.setVisible(true);
        txt_contactoCorreo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_cliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cb_contacto = new javax.swing.JComboBox<>();
        txt_contactoCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_archivo = new javax.swing.JTextField();
        btn_archivo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btn_enviar = new javax.swing.JButton();
        txt_contactoCelular = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, 640, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hacer pedido");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 640, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cliente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 101, -1, -1));

        txt_cliente.setEditable(false);
        add(txt_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 123, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("¿Como te contactamos?");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 101, -1, -1));

        cb_contacto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_contacto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celular", "Correo" }));
        cb_contacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_contactoActionPerformed(evt);
            }
        });
        add(cb_contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 123, 128, -1));

        txt_contactoCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_contactoCorreoFocusLost(evt);
            }
        });
        add(txt_contactoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 161, 128, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Sube tu tarea aquí");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 200, -1, -1));

        txt_archivo.setEditable(false);
        add(txt_archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 234, 213, -1));

        btn_archivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_archivo.setText("Cargar archivo");
        btn_archivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_archivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_archivoMouseClicked(evt);
            }
        });
        add(btn_archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 234, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Subir un único archivo en PDF");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Mensaje (especificar la fecha de entrega)");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 310, -1, -1));

        jScrollPane1.setBorder(null);

        txtArea.setBackground(new java.awt.Color(204, 204, 204));
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtArea.setForeground(new java.awt.Color(0, 0, 0));
        txtArea.setRows(5);
        txtArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 332, 320, 110));

        btn_enviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_enviar.setText("ENVIAR");
        btn_enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_enviarMouseClicked(evt);
            }
        });
        add(btn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 210, 80));

        txt_contactoCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contactoCelularKeyTyped(evt);
            }
        });
        add(txt_contactoCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 161, 128, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_archivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_archivoMouseClicked
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(".PDF", "pdf");
        fc.setFileFilter(filtro);
        int seleccion = fc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            fichero = fc.getSelectedFile();
            this.txt_archivo.setText(fichero.getName());
            nombreArchivo = fichero.getName();
        }
        try {
            fis = new FileInputStream(fichero);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(pnlHacerPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_archivoMouseClicked


    private void cb_contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_contactoActionPerformed
        if (cb_contacto.getSelectedItem().equals("Celular")) {
            txt_contactoCorreo.setText("");
            txt_contactoCorreo.setVisible(false);
            txt_contactoCelular.setVisible(true);
        } else if (cb_contacto.getSelectedItem().equals("Correo")) {
            txt_contactoCelular.setText("");
            txt_contactoCelular.setVisible(false);
            txt_contactoCorreo.setVisible(true);
        }
    }//GEN-LAST:event_cb_contactoActionPerformed

    private void txt_contactoCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactoCelularKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            evt.consume();
        }
        if (txt_contactoCelular.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_contactoCelularKeyTyped

    private void txt_contactoCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contactoCorreoFocusLost
        if (isEmail(txt_contactoCorreo.getText())) {

        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar un correo");
            txt_contactoCorreo.requestFocus();
        }
    }//GEN-LAST:event_txt_contactoCorreoFocusLost

    private void txtAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaKeyTyped
        if (txtArea.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAreaKeyTyped

    private void btn_enviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_enviarMouseClicked

        if (txt_contactoCelular.getText().equals("") && txt_contactoCorreo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe agregar una forma de contacto");
        } else {
            if (txt_archivo.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Debe agregar el archivo de la tarea");
            } else {
                if (txtArea.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Por favor ingrese un mensaje (proporcionar fecha de entrega)");
                } else {
                    //enviando datos a la base de datos
                    //en proceso - aceptado - terminado - cancelado
                    cliente = txt_cliente.getText().trim();
                    numero = txt_contactoCelular.getText().trim();
                    correo = txt_contactoCorreo.getText().trim();
                    mensaje = txtArea.getText().trim();
                    estado = "en proceso";
                    if(numero.equals("")){
                        numero = "VACIO";
                    }
                    if(correo.equals("")){
                        correo = "VACIO";
                    }
                    try {
                        Connection cn = Conexion.conectar();
                        PreparedStatement pst = cn.prepareStatement("insert into tareasusuarios (cliente,celular,correo,archivo,nombreArchivo,mensaje,estado) values (?,?,?,?,?,?,?)");
                        pst.setString(1, cliente);                        
                        pst.setString(2, numero);                        
                        pst.setString(3, correo);
                        pst.setBinaryStream(4, fis, (int) fichero.length());
                        pst.setString(5, nombreArchivo);
                        pst.setString(6, mensaje);
                        pst.setString(7, estado);
                        pst.executeUpdate();
                        limpiar();
                        JOptionPane.showMessageDialog(this, "Tarea recibida, Nos pondremos en contacto con usted pronto!", "Tarea", JOptionPane.INFORMATION_MESSAGE);
                    } catch (SQLException e) {
                        System.err.println("Error al enviar los datos a la base de datos " + e);
                        JOptionPane.showMessageDialog(this, "El archivo excede el tamaño permitido", "Tarea", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_btn_enviarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_archivo;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JComboBox<String> cb_contacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txt_archivo;
    private javax.swing.JTextField txt_cliente;
    private javax.swing.JTextField txt_contactoCelular;
    private javax.swing.JTextField txt_contactoCorreo;
    // End of variables declaration//GEN-END:variables

    public boolean isEmail(String correo) {
        Pattern pattern = Pattern
                .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

        Matcher mather = pattern.matcher(correo);
        if (mather.find() == true) {
            return true;
        } else {
            return false;
        }
    }

    public void limpiar() {
        txt_archivo.setText("");
        txt_contactoCelular.setText("");
        txt_contactoCorreo.setText("");
        txtArea.setText("");
    }

}
