/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import conexion.Conexion;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import ventanas.ModificarInformacionAdmin;

/**
 *
 * @author RojeruSan
 */
public class pnlInformacionAdmin extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public static String usuario = "";
    DefaultTableModel model = new DefaultTableModel();
    Object[] fila;
    public pnlInformacionAdmin() {
        initComponents();
        fila = new Object[2];
        tbl_informacion = new JTable(model);
        jScrollPane2.setViewportView(tbl_informacion);
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from cuentasusuarios");
            ResultSet rs = pst.executeQuery();
            model.addColumn("Usuario");
            model.addColumn("Contraseña");            
            while (rs.next()) {
                for (int i = 0; i < 2; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al extraer los datos " + e);
        }
        
        tbl_informacion.addMouseListener(new MouseAdapter(){
            
            @Override
            public void mouseClicked(MouseEvent e){
                int fila_point = tbl_informacion.rowAtPoint(e.getPoint());                
                int columna_usuario = 0;
                if(fila_point > -1){
                    usuario = (String)model.getValueAt(fila_point, columna_usuario);
                    ModificarInformacionAdmin modificarInfo = new ModificarInformacionAdmin();
                    modificarInfo.setVisible(true);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_cliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_informacion = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, 640, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Informacion Clientes");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 640, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cliente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 101, -1, -1));

        txt_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_clienteKeyTyped(evt);
            }
        });
        add(txt_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 123, 116, -1));

        tbl_informacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(tbl_informacion);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 160, 590, 290));
    }// </editor-fold>//GEN-END:initComponents

    TableRowSorter trs;
    private void txt_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_clienteKeyTyped
        txt_cliente.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txt_cliente.getText(), 0));
            }
        });
        trs = new TableRowSorter(model);
        tbl_informacion.setRowSorter(trs);
    }//GEN-LAST:event_txt_clienteKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_informacion;
    private javax.swing.JTextField txt_cliente;
    // End of variables declaration//GEN-END:variables
}
