/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import conexion.Conexion;
import ventanas.ModifcarPedidosAdmin;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author RojeruSan
 */
public class pnlPedidosAdmin extends javax.swing.JPanel {

    
    public static String userCliente = "";
    public static String id_cliente = "";
    DefaultTableModel model = new DefaultTableModel();
    Object[] fila;
    
    public pnlPedidosAdmin() {
        initComponents();
        fila = new Object[7];
        tbl_pedidosClientes = new JTable(model);
        jScrollPane2.setViewportView(tbl_pedidosClientes);
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select id_tarea,cliente,celular,correo,nombreArchivo,mensaje,estado from tareasusuarios");
            ResultSet rs = pst.executeQuery();

            model.addColumn("ID");
            model.addColumn("Cliente");
            model.addColumn("Celular");
            model.addColumn("Correo");
            model.addColumn("Archivo");
            model.addColumn("Mensaje");
            model.addColumn("Estado");

            while (rs.next()) {
                for (int i = 0; i < 7; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al extraer los datos " + e);
        }
        
        tbl_pedidosClientes.addMouseListener(new MouseAdapter(){
            
            @Override
            public void mouseClicked(MouseEvent e){
                int fila_point = tbl_pedidosClientes.rowAtPoint(e.getPoint());
                int columna_id = 0;
                int columna_point = 1;
                
                if(fila_point > -1){
                    id_cliente = Integer.toString((int) model.getValueAt(fila_point, columna_id));
                    userCliente = (String)model.getValueAt(fila_point, columna_point);
                    ModifcarPedidosAdmin modificarPedidos = new ModifcarPedidosAdmin();
                    modificarPedidos.setVisible(true);
                }
            }
        });
    }

    /**
     * Creates new form pnlHome
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_cliente = new javax.swing.JTextField();
        btn_actualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_pedidosClientes = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, 640, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pedidos clientes");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 640, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cliente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 101, -1, -1));

        txt_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_clienteKeyTyped(evt);
            }
        });
        add(txt_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 123, 140, -1));

        btn_actualizar.setText("Actualizar");
        btn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseClicked(evt);
            }
        });
        add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 123, -1, -1));

        tbl_pedidosClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(tbl_pedidosClientes);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 620, 180));
    }// </editor-fold>//GEN-END:initComponents

    TableRowSorter trs;
    private void txt_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_clienteKeyTyped

        txt_cliente.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txt_cliente.getText(), 0));
            }
        });
        trs = new TableRowSorter(model);
        tbl_pedidosClientes.setRowSorter(trs);
    }//GEN-LAST:event_txt_clienteKeyTyped

    private void btn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseClicked
        model.setRowCount(0);
        try {
            Connection cn4 = Conexion.conectar();
            PreparedStatement pst4 = cn4.prepareStatement("select id_tarea,cliente,celular,correo,nombreArchivo,mensaje,estado from tareasusuarios");
            ResultSet rs4 = pst4.executeQuery();

            while (rs4.next()) {
                Object[] fila = new Object[7];
                for (int i = 0; i < 7; i++) {
                    fila[i] = rs4.getObject(i + 1);
                }
                model.addRow(fila);
            }
        } catch (SQLException e) {
            System.err.println("Error al actualizar datos "+e);
        }
    }//GEN-LAST:event_btn_actualizarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_pedidosClientes;
    private javax.swing.JTextField txt_cliente;
    // End of variables declaration//GEN-END:variables

}