/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RojeruSan
 */
public class pnlTerminadosAdmin extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    DefaultTableModel model = new DefaultTableModel();
    Object[] fila;
    String aux = "Terminado";
    public pnlTerminadosAdmin() {
        initComponents();
        fila = new Object[7];
        tbl_terminados = new JTable(model);
        jScrollPane2.setViewportView(tbl_terminados);
         try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select id_tarea,cliente,celular,correo,nombreArchivo,mensaje,estado from tareasusuarios where estado = '"+aux+"'");
            ResultSet rs = pst.executeQuery();

            model.addColumn("ID");
            model.addColumn("Cliente");
            model.addColumn("Celular");
            model.addColumn("Correo");
            model.addColumn("Archivo");
            model.addColumn("Mensaje");
            model.addColumn("Estado");

            while (rs.next()) {
                for (int i = 0; i < 7; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al extraer los datos " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_terminados = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, 640, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pedidos terminados");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 6, 510, -1));

        btn_actualizar.setText("Actualizar");
        btn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseClicked(evt);
            }
        });
        add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        tbl_terminados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(tbl_terminados);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 620, 290));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseClicked
        model.setRowCount(0);
        try {
            Connection cn2 = Conexion.conectar();
            PreparedStatement pst2 = cn2.prepareStatement("select id_tarea,cliente,celular,correo,nombreArchivo,mensaje,estado from tareasusuarios where estado = '"+aux+"'");
            ResultSet rs2 = pst2.executeQuery();

            while (rs2.next()) {
                Object[] fila = new Object[7];
                for (int i = 0; i < 7; i++) {
                    fila[i] = rs2.getObject(i + 1);
                }
                model.addRow(fila);
            }
        } catch (SQLException e) {
            System.err.println("Error al actualizar datos "+e);
        }
    }//GEN-LAST:event_btn_actualizarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_terminados;
    // End of variables declaration//GEN-END:variables
}
